"""
This plugin allows you to use links to API documentation of a Python package documented by Nedoc.

Use a link with text wrapped by backticks (`) and set the link URL to a key contained in `map.json`.
`map.json` is generated by Nedoc if you use the `create_map_json = True` configuration in `nedoc.conf`.

Links cannot span a line! Keep them on a single line.

Example:
The [`Box`](elsie.box.Box) class is awesome.
"""
import os
from os.path import abspath, dirname
import re
import json

from mkdocs.plugins import BasePlugin
from mkdocs.structure.pages import Page

CURRENT_DIR = dirname(abspath(__file__))
DOCS_DIR = dirname(dirname(CURRENT_DIR))

MAP_FILE = os.path.join(DOCS_DIR, "apidoc", "map.json")
MAP = {}

if os.path.isfile(MAP_FILE):
    with open(MAP_FILE) as f:
        MAP = json.load(f)
else:
    print("WARNING: docs/apidoc/map.json file is missing")


LINK_REGEX = re.compile(r"\[`.*?`\]\((.*?)\)")


class NedocPlugin(BasePlugin):
    def __init__(self):
        self.site_url = None

    def on_config(self, config, **kwargs):
        self.site_url = config.get("site_url") or "/"
        self.site_url = f"{self.site_url}apidoc"

    def on_page_markdown(self, src: str, page, config, *args, **kwargs):
        # TODO: use Markdown parser
        lines = []
        for line in src.splitlines(keepends=False):
            # Iterate from the end to make replacing substrings easier
            for match in reversed(list(LINK_REGEX.finditer(line))):
                link_key = match.group(1)
                link_url = MAP.get(link_key)
                if link_url:
                    url = f"{self.site_url}/{link_url}"
                    start, end = match.span(1)
                    line = line[:start] + url + line[end:]
                else:
                    print(f"WARNING: link key {link_key} not found")
            lines.append(line)
        return "\n".join(lines)
